### PR TITLE
Added the Ability to change Single Star Images in the Rating Control

### PR DESCRIPTION
**Pull request by martinjuhasz**
so this option is probably worth a pull?
i needed it for my own project so i forked your repo.

checkout the demo project.

### CODE REVIEW

**Comment by dlinsin** [comment]
Thanks for the contribution Martin! 

Looking at your code I had an idea: What do you think about creating an _init_ method in `DLStarRatingControl` that takes an `NSArray` of images and highlighted images, where the position in the Array depicts the index where the images are set?

``` objective-c

// _default and _highlighted contain NSString* instances of images names
- (id)initWithFrame:(CGRect)frame defaultStars:(NSArray*)_default andHighlightedStars(NSArray*)_highlighted;

```

I think there wouldn't be any changes in `DLStarView` necessary, you could just hook up to the existing methods.

**Comment by martinjuhasz** [comment]
good idea!

**Comment by dlinsin** [comment]
> good idea!

I'd appreciate if you could update your Pull Request with the discussed changes.

**Comment by martinjuhasz** [comment]
in your case, what would you do, if you want do use default stars, but the last star should be a special one?

set the same star 4 times ?

**Comment by dlinsin** [comment]
> in your case, what would you do, if you want do use default stars, but the last star should be a special one?
> 
> set the same star 4 times ?

Yeah, I guess that would not work with my suggested solution. Especially, because `NSArray` doesn't support nil values. I can't think of better way than your implementation right now to have the same flexibility, but doing all your setup with the `init` call.

**Pull request merged**
